"""add pr context columns to review_runs

Revision ID: 42ae44a22f28
Revises: c5404d77f880
Create Date: 2026-07-25 10:33:04.381036

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42ae44a22f28"
down_revision: Union[str, Sequence[str], None] = "c5404d77f880"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("review_runs", sa.Column("pr_owner", sa.String(), nullable=True))
    op.add_column("review_runs", sa.Column("pr_repo", sa.String(), nullable=True))
    op.add_column("review_runs", sa.Column("pr_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_runs", "pr_number")
    op.drop_column("review_runs", "pr_repo")
    op.drop_column("review_runs", "pr_owner")
    # ### end Alembic commands ###
