"""add approval_status to review_items
Revision ID: c5404d77f880
Revises: 27ad833a32d6
Create Date: 2026-07-25 09:45:33.856147
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5404d77f880"
down_revision: Union[str, Sequence[str], None] = "27ad833a32d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_items",
        sa.Column(
            "approval_status",
            sa.String(),
            nullable=False,
            server_default="proposed",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_items", "approval_status")
    # ### end Alembic commands ###
